version: '3.1'

services:
  mongodatabase:
    image: mongo
    container_name: mongoDB
    restart: always
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=userAdmin
      - MONGO_INITDB_ROOT_PASSWORD=userPassword
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: